language: python
python: 
- 2.7
- 3.5
- 3.6
env:
- AWS_REGION=us-west-2
before_script:
- source ./travis_build.sh
- pip install tox-travis
- cd sagemaker-pyspark-sdk
script:
- tox

matrix:
  include:
    - language: scala
      scala: 2.11.7
      env:
        - AWS_REGION=us-west-2
      before_script:
        - cd sagemaker-spark-sdk
      script:
        - sbt clean coverage test coverageReport
