version: 0.2

phases:
  install:
    commands:
      # install openjdk-8
      - apt-get update
      - apt-get -y install openjdk-8-jdk
      - update-java-alternatives -s java-1.8.0-openjdk-amd64
      - export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64/bin

      # install sbt launcher
      - curl -LO https://github.com/sbt/sbt/releases/download/v1.7.1/sbt-1.7.1.tgz
      - tar -xf sbt-*.tgz
      - export PATH=$CODEBUILD_SRC_DIR/sbt/bin/:$PATH
      - cd $CODEBUILD_SRC_DIR/sagemaker-spark-sdk
      - sbt -Dsbt.log.noformat=true sbtVersion scalaVersion

  build:
    commands:
      - export SBT_OPTS="-Xms1024M -Xmx4G -Xss2M -XX:MaxMetaspaceSize=2G"

      # ignore reuse error to allow retry of this build stage
      # when sonatype step has transient error
      - publish-pypi-package --ignore-reuse-error $CODEBUILD_SRC_DIR_ARTIFACT_1/sagemaker-pyspark-sdk/dist/sagemaker_pyspark-*.tar.gz
      - publish-sonatype-package $CODEBUILD_SRC_DIR_ARTIFACT_1/sagemaker-spark-sdk
